# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "preloadenabler"
version = "2.1.0"
languages = ["CXX"]
cmake-after = """
set(VCPKG_TARGET_TRIPLET x86-windows-static)
"""

[options]
SAFETYHOOK_FETCH_ZYDIS = true

[variables]
CMAKE_CXX_STANDARD = "23"
CMAKE_CXX_STANDARD_REQUIRED = true

[fetch-content]
safetyhook = { git = "https://github.com/cursey/safetyhook", tag = "v0.1.3" }
toml11 = { git = "https://github.com/ToruNiina/toml11", tag = "v3.7.1" }
spdlog = { git = "https://github.com/gabime/spdlog", tag = "v1.12.0" }

[target.preloadenabler]
type = "shared"
sources = ["src/**.cpp", "include/**.hpp"]
include-directories = ["include"]
compile-features = ["cxx_std_23"]
link-libraries = [
    "safetyhook",
    "toml11",
    "spdlog",
    "wininet",
]

[[install]]
targets = ["preloadenabler"]
destination = "bin"
